FROM mcr.microsoft.com/dotnet/sdk:10.0 AS base
WORKDIR /app
EXPOSE 5002
ENV ASPNETCORE_URLS=http://*:5002

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["AuthService.Application/AuthService.Application.csproj", "AuthService.Application/"]

RUN dotnet restore "AuthService.Application/AuthService.Application.csproj"
COPY . .
WORKDIR "/src/AuthService.Application"
RUN dotnet build "AuthService.Application.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "AuthService.Application.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AuthService.Application.dll"]